<?php
// 테스트용
define("URL", "http://www.adchunha.com/API_V1/test_send");
//define("URL", "http://www.adchunha.com/API_V1/send");
// 아이디
define("ID", "113979");
// 비밀번호
define("PW", "113979");
// 전송키
define("KEY", "AD1139791139");
// 주문자정보
define("ORDERER", [
     "name"  => "(주)굿프린팅"
    ,"tel"   => "02-2260-9022"
    ,"hp"    => "010-5057-3759"
    ,"hp2"   => "010-5057-3759"
    ,"email" => "hshyun0232@dprinting.biz"
]);
// 도메인
define("FILE_URL", "http://yesprinting.co.kr/api/ao_adchunha_file_down.php");
//define("FILE_URL", "http://devadmin.yesprinting.co.kr/api/ao_adchunha_file_down.php");
// 아이템 코드
define("ITEM_CODE", [
     "002001001" => "1202"
    ,"002002001" => "1202"
    ,"002002002" => "1202"
    ,"002002003" => "1202"

    ,"002002004" => "1201"

    ,"002004001" => "1203"

    ,"002005001" => "1201"
    ,"002005002" => "1201"
    ,"002005003" => "1201"
]);
// 아이템 이름
define("ITEM_NAME", [
     "002001001" => "미니패트배너"
    ,"002002001" => "패트PET배너"
    ,"002002002" => "투명배너"
    ,"002002003" => "매쉬배너"

    ,"002002004" => "가로등배너"

    ,"002004001" => "등신대"

    ,"002005001" => "게릴라현수막"
    ,"002005002" => "족자현수막"
    ,"002005003" => "현수막통합주문"
]);
