<?php
/**
 * Created by PhpStorm.
 * User: Hyeonsik Cho
 * Date: 2017-11-08
 * Time: 오후 4:32
 */
include_once(INC_PATH . "/classes/dprinting/StateManager/abstracts/AbstractOrderByCountState.php");

class AfterProcessWaitingState extends AbstractOrderByCountState
{
    public function init($param) {
        // 필수정보
        $this->origin_state = $param['origin_state'];
        $this->to_state = "2530";
        parent::init($param);
    }

    public function ToNextState()
    {
        parent::ToNextState();
    }

    public function RollbackState()
    {
        // TODO: Change the autogenerated stub
        parent::RollbackState();
    }
}