<?php
/**
 * Created by PhpStorm.
 * User: Hyeonsik Cho
 * Date: 2017-11-08
 * Time: 오후 4:31
 */

class AfterProcessingState extends AbstractOrderByCountState
{
    public function init($param) {
        // 필수정보
        $this->origin_state = $param['origin_state'];
        if($param['kind'] == "hold")
            $this->to_state = "2560";
        else if($param['kind'] == "progress")
            $this->to_state = "3120";
        parent::init($param);
    }

    public function ToNextState()
    {
        parent::ToNextState();
    }

    public function RollbackState()
    {
        // TODO: Change the autogenerated stub
        parent::RollbackState();
    }
}