<?php
/**
 * Created by PhpStorm.
 * User: Hyeonsik Cho
 * Date: 2017-10-28
 * Time: 오후 6:05
 */

include_once(INC_PATH . "/classes/dprinting/StateManager/abstracts/AbstractOrderByCountState.php");

class PrintWaitingState extends AbstractOrderByCountState
{
    var $sheet_typset_seqno;

    public function init($param) {
        // 필수정보
        $this->sheet_typset_seqno = $param['sheet_typset_seqno'];
        $this->origin_state = $param['origin_state'];
        $this->to_state = "2330";

        //parent::init($param);
    }

    public function ToNextState()
    {
        $param['sheet_typset_seqno'] = $this->sheet_typset_seqno;
        $param['to_state'] = $this->to_state;
        $param['origin_state'] = $this->origin_state;
        $this->dao->updateTypsetState($this->conn, $param);

        $order_detail_file_nums = $this->dao->selectOrderDetailCountFileSeqno($this->conn, $param);
        foreach($order_detail_file_nums as $order_detail_file_num) {
            $param['order_detail_file_num'] = $order_detail_file_num;
            if($this->dao->isIncludedTypset($this->conn, $param)) {
                $this->order_detail_file_num = $order_detail_file_num;
                parent::ToNextState();
            }
        }
    }

    public function RollbackState()
    {
        // TODO: Change the autogenerated stub
        parent::RollbackState();
    }
}