<?
//쿠폰 파일 html
function getFileHtml($param) {

    $html = <<<VIEWHTML

                        <div id="file_area">
                        <input type="hidden" nmae="file_seqno" id="file_seqno" value="$param[file_seqno]" />
                        <label class="fix_width100"> </label>
                        <label class="control-label cp blue_text01"><a href="/common/cp_file_down.php?seqno=$param[file_seqno]">$param[file_name]</a>
                        <img src="/design_template/images/btn_circle_x_red.png" onclick="delCpFile($param[file_seqno]);" style="cursor:pointer;"> 
                        </label>
                        <br /> 
                        </div>

VIEWHTML;

    return $html;

}

//발행 매수 html
function getAmtHtml($param) {

    $html = <<<VIEWHTML
 
                        <div id="amt_area" $param[amt_dspl]>
                        <label class="control-label fix_width79 tar">발행매수</label><label class="fix_width20 fs14 tac">:</label>
                        <input type="text" id="public_amt" name="public_amt" maxlength="10" class="input_co5 fix_width170" value="$param[public_amt]">
                        <br />
                        </div>

VIEWHTML;

    return $html;

}

//쿠폰 view html
function getCpView($param) {

    $html = <<<VIEWHTML

     <dl>
          <dt class="tit">
               <h4>쿠폰등록</h4>
          </dt>
          <dt class="cls">
               <button type="button" onclick="hideRegiPopup();" class="btn btn-sm btn-danger fa fa-times"></button>
          </dt>
     </dl>  
														 	
     <div class="pop-base fl fix_width880">        
    <form name="cp_form" id="cp_form" method="post">
			  											 	 	  
          <div class="pop-content ofa">

                <ul class="form-group">
                     <li class=" fl" style="padding-right: 20px;">
                        <label class="control-label fix_width79 tar">발행종류</label><label class="fix_width20 fs14 tac">:</label>
                        <label class="control-label cp"><input type="radio" class="radio_box" name="coupon_kind" value="release_all" $param[release_all] onchange="change_coupon_kind();">전체발행</label>
                        <label class="control-label cp"><input type="radio" class="radio_box" name="coupon_kind" value="input_coupon" $param[input_coupon] onchange="change_coupon_kind();">입력쿠폰</label>
                        <br />
                        <label class="control-label cp" id="lb_coupon_number" style="$param[lb_coupon_number]">
                            <input maxlength="4" type="text" class="input_co5 fix_width75" name="coupon_number_1" id="coupon_number_1" value="$param[coupon_number_1]">-
                            <input maxlength="4" type="text" class="input_co5 fix_width75" name="coupon_number_2" id="coupon_number_2" value="$param[coupon_number_2]">-
                            <input maxlength="4" type="text" class="input_co5 fix_width75" name="coupon_number_3" id="coupon_number_3" value="$param[coupon_number_3]">
                        </label>
                        <br />
                        <hr class="hr_bd3">
                        <label class="control-label fix_width79 tar">쿠폰명</label><label class="fix_width20 fs14 tac">:</label>
                        <input type="text" id="pop_cp_name" name="pop_cp_name" maxlength="50" class="input_co5 fix_width170" value="$param[name]">
                        <br />
                        <hr class="hr_bd3">
                        
                        <label class="control-label fix_width79 tar">판매채널</label><label class="fix_width20 fs14 tac">:</label>
                        <select name="pop_sell_site" class="fix_width150">
                            <option selected="selected" value="GP">GP</option>
                            <option value="DP">DP</option>
                        </select> 
                        <br />
                        <hr class="hr_bd3">

                        <label class="control-label fix_width79 tar">할인내용</label><label class="fix_width20 fs14 tac">:</label>
                        <label class="control-label cp"><input type="radio" class="radio_box" name="sale_dvs" value="%" $param[per_check]>할인요율</label>
                        <label class="fix_width10"> </label>
                        <label class="control-label cp"><input maxlength="10" type="text" class="input_co5 fix_width75" name="per_val" id="per_val" value="$param[per_val]">%</label>
                        <label class="fix_width40"> </label>
                        <label class="control-label cp">최대</label>
                        <label class="control-label cp"><input maxlength="10" type="text" class="input_co5 fix_width75" name="max_discount_price" id="max_discount_price" value="$param[max_discount_price]">원</label>
                        <br />
                        <label class="fix_width100"> </label>
                        <label class="control-label cp"><input maxlength="10" type="radio" class="radio_box" name="sale_dvs" value="원" $param[won_check]>할인금액</label>
                        <label class="fix_width10"> </label>
                        <label class="control-label cp"><input maxlength="10" type="text" class="input_co5 fix_width75" name="min_order_price" id="min_order_price" value="$param[min_order_price]">원 이상 구매시</label>
                        <label class="control-label cp"><input maxlength="10" type="text" class="input_co5 fix_width75" name="won_val" id="won_val"  value="$param[won_val]">원</label>
                        <br />
                        <hr class="hr_bd3">
                        
                        <label class="control-label fix_width79 tar">유효기간</label><label class="fix_width20 fs14 tac">:</label>
                        <input placeholder="yyyy-MM-dd" class="input_co2 fix_width83 date" id="release_date" name="release_date" value="$param[release_date]">
                        <label class="control-label cp">~</label>
                        <input placeholder="yyyy-MM-dd" class="input_co2 fix_width83 date" id="expired_date" name="expired_date" value="$param[expired_date]">
                        <br />
                        <hr class="hr_bd3">


                        <!--label class="control-label fix_width79 tar">쿠폰만료일</label><label class="fix_width20 fs14 tac">:</label>
                        <label class="control-label cp"><input type="radio" class="radio_box" value="1" name="expire_dvs" $param[expire_dvs_1]>발행 후</label>
                        <label class="fix_width10"> </label>
                        <label class="control-label cp"><input type="text" maxlength="10" class="input_co5 fix_width75" name="expire_public_day" id="expire_public_day" value="$param[expire_public_day]">일</label>
                        <label class="fix_width10"> </label>
                        <br />
                        <label class="fix_width100"> </label>
                        <label class="control-label cp"><input type="radio" class="radio_box" value="2" name="expire_dvs" $param[expire_dvs_2]>날짜 지정</label>
                        <label class="control-label cp"><input placeholder="yyyy-MM-dd" class="input_co2 fix_width83 date" id="expire_extinct_date" name="expire_extinct_date" value="$param[expire_extinct_date]">에 소멸</label>
                        <br />
                        <label class="fix_width100"> </label>
                        <label class="control-label cp"><input type="radio" class="radio_box" value="3" name="expire_dvs" $param[expire_dvs_3]>만료일 없음</label>
                        <br />
                        <label class="fix_width100"> </label>
                        <label class="control-label cp red_text01">만료일은 쿠폰 노출기간 내 사용자가 발급받은 일로부터 계산됨</label>
                        <hr class="hr_bd3">

                        <label class="control-label fix_width79 tar">대상지정방식</label><label class="fix_width20 fs14 tac">:</label>
                        <label class="control-label cp"><input type="radio" class="radio_box" value="Y" onchange="showAmtArea(this.value); return false;" name="object_appoint" $param[object_y]>대상지정</label>
                        <label class="fix_width10"> </label>
                        <label class="control-label cp"><input type="radio" class="radio_box" value="N" onchange="showAmtArea(this.value); return false;" name="object_appoint" $param[object_n]>대상미지정</label>
                        <br />
                        $param[amt_html]
                        
                        <label class="control-label fix_width79 tar">노출여부</label><label class="fix_width20 fs14 tac">:</label>
                        <label class="control-label cp"><input type="radio" class="radio_box" value="Y" name="cp_expo_yn" $param[cp_expo_y] $param[cp_expo_disabled]>노출</label>
                        <label class="fix_width37"> </label>
                        <label class="control-label cp"><input type="radio" class="radio_box" value="N" name="cp_expo_yn" $param[cp_expo_n] $param[cp_expo_disabled]>미노출</label>
                        <br />                        
                        <hr class="hr_bd3">
                        
                        <label class="control-label fix_width79 tar">이미지</label><label class="fix_width20 fs14 tac">:</label>
                        <input id="upload_file" name="upload_file" class="disableInputField" placeholder="Choose File" readonly />
                        
                        <label class="fileUpload">
                            <input id="upload_btn" name="upload_btn" type="file" class="upload" />
                            <span class="btn btn-sm btn-info fa">찾아보기</span>
                        </label>
                        <div>
                            <label class="fix_width100"> </label>
                            <label class="control-label cp red_text01">
                                파일 권장 사이즈 : 440 * 480
                            </label>
                        </div>
                        <script type="text/javascript">  
                            document.getElementById("upload_btn").onchange = function () {
                            document.getElementById("upload_file").value = this.value;
                                 };
                        </script>
                        $param[file_html]
                        -->
                    </li>          
                     	  
                     <li class="fix_width450 fl" style="border-left: 1px solid #ddd;padding-left: 15px;">
                        <label class="control-label fix_width82 tar">대상상품선택</label><label class="fix_width20 fs14 tac">:</label>
                        <label class="control-label cp">
                            <input type="checkbox" class="radio_box" value="" name="cate_sortcode[]" id="cate_sortcode" onchange="clickAllSortcode()">전체
                        </label></br>
                        <label class="fix_width100"> </label>
                        $param[cate_mid]
                     </li>
                     
                </ul>

          </div> <!-- pop-content -->
     </div>
     <!-- pop-base -->
     
     <div class="clear">     
     <br />    
     	<p class="tac mt5">
          <label onclick="saveCpInfo('$param[coupon_seqno]')" class="btn btn_md fix_width120"> $param[submit]</label>          
          <label onclick="hideRegiPopup()" class="btn btn_md fix_width120"> 취소</label>          
      </p>
      <br /><br /> 	    
    </div>

    </form>
VIEWHTML;

    return $html;

}

//대상 지정 html
function getObjectView($param) {

    $html = <<<VIEWHTML

<!-- 쿠폰대상지정 팝업창 --> 
     <dl>
          <dt class="tit">
               <h4>쿠폰대상지정</h4>
          </dt>
          <dt class="cls">
               <button type="button" onclick="hideRegiPopup();" class="btn btn-sm btn-danger fa fa-times"></button>
          </dt>
     </dl>  
														 	
     <div class="pop-base fl" style="width: 1000px;">        
			  											 	 	  
          <div class="pop-content ofa fix_height800" >

                <ul class="form-group">
				     <li>
					    <div class="pop-content">								        	   
					    <label class="control-label fix_width180 tar">회원명</label> <label class="fix_width10 fs14 tac"> : </label> <input maxlength="50" id="office_nick" name="office_nick" onkeydown="loadMemberName(event, this.value, '')"  type="text" class="input_co2" style="width: 173px;" placeholder="검색창 팝업 사용">
						<label class="control-label fix_width180 tar">팀구분</label> <label class="fix_width10 fs14 tac"> : </label> <select id="depar_dvs" class="fix_width180">
                            $param[depar_html]
                        </select>
                        <br />
						<label class="control-label fix_width180 tar">회원구분</label> <label class="fix_width10 fs14 tac"> : </label> <select id="member_typ" class="fix_width180">
                        <option value="">전체</option>
                        <option value="일반회원">일반회원</option>
                        <option value="예외업체">예외업체</option>
                        </select>
						<label class="control-label fix_width180 tar">등급구분</label> <label class="fix_width10 fs14 tac"> : </label> <select id="grade_dvs" class="fix_width180">
                            $param[grade_html]
                        </select>
						<br />
					    <p class="btn-lg red_btn">
                          <a style="cursor: pointer;" onclick="loadMemberInfoList(); return false;">검색</a>
                        </p>
                     <br /><br /><br />
						<hr class="hr_bd3">
						</div>
					 </li>
					 
                     <li  class="fix_width450 fl">
                        <div class="table-body" style="width: 500px;">
                            <div class="ofa fix_height350 mb15">
                                <table class="table fix_width100f ">
    					            <thead>
    					               <tr>
					                        <th class="bm2px"><input type="checkbox" class="check_box" name="all_member_chk" id="all_member_chk" onclick="allCheck('all_member_chk', 'member_list');"></th>
    					            	    <th class="bm2px">회원명</th>
    					            	    <th class="bm2px">등급</th>					            	    
											<th class="bm2px">팀구분</th>
											<th class="bm2px">회원구분</th>
											<th class="bm2px">핸드폰번호</th>
    					            	</tr>					                      				
    					             </thead>
    					             <tbody id="member_list">	
                                     <tr>
                                        <td colspan="6">검색된 내용이 없습니다.</td>
                                    </tr>
    					             </tbody>
    					        </table>
                            </div>
                        </div>
                     </li>
                     
                     <li class="fix_width48 fl">
                        <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
                        <button type="button" onClick="addMemberAppoint()" class="btn btn-sm btn-info">▶</button>
                     </li>
                     	  
                     <li  class="fix_width450 fl">
                        <div class="table-body" style="width: 332px;">
                            <div class="ofa fix_height350 mb15">
                                <table class="table fix_width100f ">
    					            <thead>
    					               <tr>
					                      	<th class="bm2px"><input type="checkbox" class="check_box" name="all_appoint_chk" id="all_appoint_chk" onclick="allCheck('all_appoint_chk', 'appoint_list');"></th>
    					            	    <th class="bm2px">회원명</th>
    					            	    <th class="bm2px">쿠폰번호</th>					            	    
    					            	</tr>					                      				
    					             </thead>
    					             <tbody id="appoint_list">	
                                    $param[issue_list]
    					             </tbody>
    					        </table>
    					        
                            </div>
                            <button class="btn btn_pu fix_width75 fix_height30 bred fs12" onclick="delAppointMember(); return false;">삭제</button>
    					    <br />
                        </div>
                     </li>
                     
                </ul>

          </div> <!-- pop-content -->
     </div>
     <!-- pop-base -->
     
     <div class="clear">     
     	<p class="tac mt5">
          <label class="btn btn_md fix_width120" onclick="addCpIssue()"> 발급</label>          
      </p>
      <br /><br />    	    
          
    </div>
        
<!-- 쿠폰대상지정 팝업창 -->  



VIEWHTML;

    return $html;

}

?>
