<?
include_once(INC_PATH . '/com/nexmotion/job/nimda/common/BusinessCommonDAO.inc');

/*
 * Copyright (c) 2017 Nexmotion, Inc.
 * All rights reserved.
 *
 * 영업 - 견적관리DAO
 *
 * REVISION HISTORY (reverse chronological order)
 *=============================================================================
 * 2017/05/19 이청산 생성
 *=============================================================================
 */
 class EstiMngDAO extends BusinessCommonDAO {
    


}
?>
