<?
include_once(INC_PATH . '/com/nexmotion/job/nimda/common/NimdaCommonDAO.inc');
include_once(INC_PATH . "/com/nexmotion/html/nimda/dataproc_mng/bulletin_mng/BulletinMngHTML.inc");

class BulletinMngDAO extends NimdaCommonDAO {

    /**
     * @brief 생성자
     *
     */
    function __construct() {
    }

    /*
     * 팝업 관리 list Select 
     * $conn : DB Connection
     * return : resultSet 
     */ 
    function selectPopupList($conn, $param) {

        if (!$this->connectionCheck($conn)) return false; 
        $param = $this->parameterArrayEscape($conn, $param);
        $query  = "\n    SELECT  post_start_date";
        $query .= "\n           ,post_end_date";
        $query .= "\n           ,name";
        $query .= "\n           ,use_yn";
        $query .= "\n           ,file_path";
        $query .= "\n           ,wid_size";
        $query .= "\n           ,vert_size";
        $query .= "\n           ,save_file_name";
        $query .= "\n           ,origin_file_name";
        $query .= "\n           ,start_hour";
        $query .= "\n           ,end_hour";
        $query .= "\n           ,url_addr";
        $query .= "\n           ,target_yn";
        $query .= "\n           ,popup_admin_seqno";
        $query .= "\n      FROM  popup_admin";

        
        //팝업 관리 일련번호가 있을때
        if ($this->blankParameterCheck($param, "popup_seqno")) {

            $query .= "\n     WHERE popup_admin_seqno = " . $param["popup_seqno"];

        }

        $result = $conn->Execute($query);

        return $result;
    }

    /*
     * 공지 관리 list Select 
     * $conn : DB Connection
     * return : resultSet 
     */ 
    function selectNoticeList($conn, $param) {

        if (!$this->connectionCheck($conn)) return false; 
        $param = $this->parameterArrayEscape($conn, $param);
        $query  = "\n    SELECT  A.title";
        $query .= "\n           ,A.dvs";
        $query .= "\n           ,A.regi_date";
        $query .= "\n           ,A.hits";
        $query .= "\n           ,A.notice_seqno";
        $query .= "\n           ,B.name";
        $query .= "\n      FROM  notice A";
        $query .= "\n           ,empl_human_info B";
        $query .= "\n     WHERE  A.empl_seqno = B.empl_seqno";
        
        //팝업 관리 일련번호가 있을때
        if ($this->blankParameterCheck($param, "notice_seqno")) {

            $query .= "\n       AND notice_seqno = " . $param["notice_seqno"];

        }

        $query .= "\n  ORDER BY  A.notice_seqno DESC";

        //limit 조건
        if ($this->blankParameterCheck($param ,"start") && $this->blankParameterCheck($param ,"end")) {
 
            $param["start"] = substr($param["start"], 1, -1);
            $param["end"] = substr($param["end"], 1, -1); 

            $query .= "\n LIMIT " . $param["start"] . ",";
            $query .= $param["end"]; 
        }

        $result = $conn->Execute($query);

        return $result;
    }

    /*
     * 공지 관리 list Count 
     * $conn : DB Connection
     * return : resultSet 
     */ 
    function countNoticeList($conn, $param) {

        if (!$this->connectionCheck($conn)) return false; 
        $param = $this->parameterArrayEscape($conn, $param);
        $query  = "\n    SELECT  count(*) as cnt";
        $query .= "\n      FROM  notice A";
        $query .= "\n           ,empl B";
        $query .= "\n     WHERE  A.empl_seqno = B.empl_seqno";
        
        //팝업 관리 일련번호가 있을때
        if ($this->blankParameterCheck($param, "notice_seqno")) {

            $query .= "\n       AND notice_seqno = " . $param["notice_seqno"];

        }

        $result = $conn->Execute($query);

        return $result;
    }

    /*
     * FAQ 관리 list Select 
     * $conn : DB Connection
     * return : resultSet 
     */ 
    function selectFaqList($conn, $param) {

        if (!$this->connectionCheck($conn)) return false; 
        $param = $this->parameterArrayEscape($conn, $param);
        $query  = "\n    SELECT  SQL_CALC_FOUND_ROWS";
        $query .= "\n            A.title";
        $query .= "\n           ,A.sort";
        $query .= "\n           ,A.regi_date";
        $query .= "\n           ,A.hits";
        $query .= "\n           ,A.faq_seqno";
        $query .= "\n      FROM  faq A";
        $query .= "\n     WHERE  1 = 1";
        
        //팝업 관리 일련번호가 있을때
        if ($this->blankParameterCheck($param, "faq_seqno")) {

            $query .= "\n       AND faq_seqno = " . $param["faq_seqno"];

        }

        $query .= "\n  ORDER BY  A.faq_seqno DESC";

        //limit 조건
        if ($this->blankParameterCheck($param ,"start") && $this->blankParameterCheck($param ,"end")) {
 
            $param["start"] = substr($param["start"], 1, -1);
            $param["end"] = substr($param["end"], 1, -1); 

            $query .= "\n LIMIT " . $param["start"] . ",";
            $query .= $param["end"]; 
        }

        $result = $conn->Execute($query);

        return $result;
    }


    /*
     * 메인베너관리
     * $conn : DB Connection
     * return : resultSet 
     */ 
    function updateMbannerUseY($conn, $param) {

        if (!$this->connectionCheck($conn)) {
            return false; 
        }

        $param = $this->parameterArrayEscape($conn, $param);

        $query  = "\n    UPDATE  main_banner";
        $query .= "\n       SET  use_yn = 'Y'";
        $query .= "\n     WHERE  seq <= " . $param["seq"];
        
        $result = $conn->Execute($query);

        if ($result === FALSE) {
            return false;
        } else {
            return true;
        }
    }

    /*
     * 메인베너관리
     * $conn : DB Connection
     * return : resultSet 
     */ 
    function updateMbannerUseN($conn, $param) {

        if (!$this->connectionCheck($conn)) {
            return false; 
        }

        $param = $this->parameterArrayEscape($conn, $param);

        $query  = "\n    UPDATE  main_banner";
        $query .= "\n       SET  use_yn = 'N'";
        $query .= "\n     WHERE  seq > " . $param["seq"];
        
        $result = $conn->Execute($query);

        if ($result === FALSE) {
            return false;
        } else {
            return true;
        }
    }
}
?>
