<?
// 회사 정보정의
define("BASIC_COM_INFO", [
    // 상호
     "name"        => "(주)굿프린팅"
    // 대표번호
    ,"repre_phone" => "02-2260-9000"
    // 대표자명
    ,"repre_name" => "김시향"
    // 사업자등록번호
    ,"licensee_num" => "201-86-07857"
    // 주소
    ,"addr" => "서울특별시 성동구 성수동1가 656-1748"
    // 통신판매업신고
    ,"mob_regi_num" => "제2020-서울성동-3036호"
    // 정보책임관리자
    ,"indivi_info_admin" => "노병걸"
    // 팩스번호
    ,"fax_num" => "02-2260-9090"
    // 대표이메일
    ,"repre_email" => "webmaster@gprinting.co.kr"
]);

?>
