<?php
define("MAX_MIN_SIZE_ARR", [
    // 실사출력
     "002002004" => [
         "PAPER" => false
        ,"MIN_WID"  => 0
        ,"MIN_VERT" => 0
        ,"MAX_WID"  => 520
        ,"MAX_VERT" => 750
    ]
    ,"002005001" => [
         "PAPER" => false
        ,"MIN_WID"  => 400
        ,"MIN_VERT" => 400
        ,"MAX_WID"  => 50000
        ,"MAX_VERT" => 1800
    ]
    ,"002005002" => [
         "PAPER" => false
        ,"MIN_WID"  => 400
        ,"MIN_VERT" => 400
        ,"MAX_WID"  => 50000
        ,"MAX_VERT" => 1800
    ]
    ,"002005003" => [
         "PAPER" => false
        ,"MIN_WID"  => 400
        ,"MIN_VERT" => 400
        ,"MAX_WID"  => 50000
        ,"MAX_VERT" => 1800
    ]
    // 코팅명함
    ,"003001001" => [
         "PAPER" => false
        ,"MIN_WID"  => 0
        ,"MIN_VERT" => 0
        ,"MAX_WID"  => 520
        ,"MAX_VERT" => 750
    ]
    ,"003001002" => [
         "PAPER" => false
        ,"MIN_WID"  => 0
        ,"MIN_VERT" => 0
        ,"MAX_WID"  => 600
        ,"MAX_VERT" => 900
    ]
    ,"003002001" => [
         "PAPER" => false
        ,"MIN_WID"  => 0
        ,"MIN_VERT" => 0
        ,"MAX_WID"  => 500
        ,"MAX_VERT" => 700
    ]
    // 컬러스티커
    ,"004001001" => [
         "PAPER" => false
        ,"MIN_WID"  => 0
        ,"MIN_VERT" => 0
        ,"MAX_WID"  => 920
        ,"MAX_VERT" => 620
    ]
    ,"004001001" => [
        "PAPER" => "크라프트"
        ,"MIN_WID"  => 60
        ,"MIN_VERT" => 40
        ,"MAX_WID"  => 760
        ,"MAX_VERT" => 500
    ]
    ,"004001001" => [
        "PAPER" => "유포지"
        ,"MIN_WID"  => 60
        ,"MIN_VERT" => 40
        ,"MAX_WID"  => 760
        ,"MAX_VERT" => 500
    ]
    ,"004001001" => [
        "PAPER" => "은데드롱"
        ,"MIN_WID"  => 60
        ,"MIN_VERT" => 40
        ,"MAX_WID"  => 760
        ,"MAX_VERT" => 500
    ]
    ,"004001001" => [
        "PAPER" => "투명데드롱"
        ,"MIN_WID"  => 60
        ,"MIN_VERT" => 40
        ,"MAX_WID"  => 760
        ,"MAX_VERT" => 500
    ]
    ,"004001001" => [
        "PAPER" => "모조지"
        ,"MIN_WID"  => 60
        ,"MIN_VERT" => 40
        ,"MAX_WID"  => 760
        ,"MAX_VERT" => 500
    ]
    // 특수지스티커
    ,"004002001" => [
         "PAPER" => false
        ,"MIN_WID"  => 40
        ,"MIN_VERT" => 40
        ,"MAX_WID"  => 700
        ,"MAX_VERT" => 500
    ]
    // 171217 이청산 수정, 자유형도무송 최소 사이즈는 (10,10)
    ,"004003009|크라프트" => [
         "PAPER" => false
        ,"MIN_WID"  => 10
        ,"MIN_VERT" => 10
        ,"MAX_WID"  => 720
        ,"MAX_VERT" => 510
    ]
    ,"004003009|유포지" => [
        "PAPER" => false
        ,"MIN_WID"  => 10
        ,"MIN_VERT" => 10
        ,"MAX_WID"  => 720
        ,"MAX_VERT" => 510
    ]
    ,"004003009|은무데드롱" => [
        "PAPER" => false
        ,"MIN_WID"  => 10
        ,"MIN_VERT" => 10
        ,"MAX_WID"  => 720
        ,"MAX_VERT" => 510
    ]
    ,"004003009|투명데드롱" => [
        "PAPER" => false
        ,"MIN_WID"  => 10
        ,"MIN_VERT" => 10
        ,"MAX_WID"  => 720
        ,"MAX_VERT" => 510
    ]
    ,"004003009|모조지" => [
        "PAPER" => false
        ,"MIN_WID"  => 10
        ,"MIN_VERT" => 10
        ,"MAX_WID"  => 720
        ,"MAX_VERT" => 510
    ]
    ,"004003009" => [
        "PAPER" => false
        ,"MIN_WID"  => 10
        ,"MIN_VERT" => 10
        ,"MAX_WID"  => 530
        ,"MAX_VERT" => 720
    ]
    // 독판전단
    ,"005002001" => [
         "PAPER" => false
        ,"MIN_WID"  => 40
        ,"MIN_VERT" => 40
        ,"MAX_WID"  => 0
        ,"MAX_VERT" => 0
    ]
    /* TODO 임시로 지정, 수정 필요함 */
    ,"007001001" => [
         "PAPER" => false
        ,"MIN_WID"  => 0
        ,"MIN_VERT" => 0
        ,"MAX_WID"  => 520
        ,"MAX_VERT" => 750
    ]
    ,"007001002" => [
         "PAPER" => false
        ,"MIN_WID"  => 0
        ,"MIN_VERT" => 0
        ,"MAX_WID"  => 520
        ,"MAX_VERT" => 750
    ]
    /* 여기까지 */
    ,"008001001" => [
         "PAPER" => false
        ,"MIN_WID"  => 0
        ,"MIN_VERT" => 0
        ,"MAX_WID"  => 520
        ,"MAX_VERT" => 750
    ]
    ,"008002002" => [
         "PAPER" => false
        ,"MIN_WID"  => 30
        ,"MIN_VERT" => 30
        ,"MAX_WID"  => 450
        ,"MAX_VERT" => 300
    ]
    ,"" => [
         "PAPER" => false
        ,"MIN_WID"  => 0
        ,"MIN_VERT" => 0
        ,"MAX_WID"  => 0
        ,"MAX_VERT" => 0
    ]
]);
